name: CI deployment; run tests via pytest

on:
    push:
        branches:
            - main

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
                python-version: 3.8
        - name: Install dependencies
          run: |
                python -m pip install --upgrade pip
                pip install pytest pytest-cov
                # If you have a requirements.txt file, you can install all your dependencies with:
                # pip install -r requirements.txt
        - name: Run tests
          run: |
                pytest app.py --cov=app --cov-report html
        - name: Deploy to GitHub Pages
          uses: JamesIves/github-pages-deploy-action@4.1.5
          with:
                branch: gh-pages
                folder: htmlcov