name: CI deployment; run tests via pytest

on:
    push:
        branches:
            - main

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
                python-version: 3.8
        - name: Install dependencies
          run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
        - name: Run tests
          run: |
                pytest test_app.py --cov=app --cov-report html
        - name: List htmlcov directory
          run: ls /home/runner/work/lake_washington_and_sammamish_temps/lake_washington_and_sammamish_temps/htmlcov
        - name: Deploy to GitHub Pages
          uses: JamesIves/github-pages-deploy-action@v4.5.0
          with:
                branch: gh-pages
                folder: htmlcov
                token: ${{ secrets.GH_PAGES_TOKEN }}
                clean: true
                single-commit: true
                silent: false
                force: false